matrix:
  # This causes the build to complete immediately upon first failure or once
  # required jobs are green.
  fast_finish: true

  # Building APK/IPA takes a long time; do not wait for them to finish.
  allow_failures:
    - env: JOB=APK
    # - env: JOB=IPA for now, we only want the apk

  include:
   # Runs unit tests without emulators.
    - env: JOB=PR
      os: linux
      language: generic
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
      before_script:
        - git clone https://github.com/flutter/flutter.git -b beta
        - ./flutter/bin/flutter doctor
        - gem install coveralls-lcov
      script:
        - ./flutter/bin/flutter test --coverage test/widget_tests/*
      after_success:
        - coveralls-lcov coverage/lcov.info

    # Builds an APK
    - env: JOB=APK
      os:
        - linux
      sudo: false
      language: android
      jdk:
        - oraclejdk8
      before_install:
        - git clone https://github.com/flutter/flutter.git -b beta
        - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
        - unzip gradle-3.5-bin.zip
      install:
        - export GRADLE_HOME=$PWD/gradle-3.5
        - export PATH=$GRADLE_HOME/bin:$PATH
        - export PATH=./flutter/bin:$PATH
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools
          - build-tools-26.0.1
          - android-26
          - sys-img-armeabi-v7a-google_apis-25
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
          before_script:




          script:
            - ./flutter/bin/flutter -v build apk

    # Builds an IPA.
    #- env: JOB=IPA
    #  os: osx
    #  language: generic
    #  osx_image: xcode8.3
    #  before_script:
    #    - pip install six
    #    - brew update
    #    - brew install --HEAD libimobiledevice
    #    - brew install ideviceinstaller
    #    - brew install ios-deploy
    #    - git clone https://github.com/flutter/flutter.git -b beta
    #  script:
    #    - ./flutter/bin/flutter -v build ios --no-codesign

cache:
  directories:
    - $HOME/.pub-cache